{% set dataset_name = "EMLOW" %}
{% set version = "8.1" %}
{% set sha256 = "5ee3cca3767768fc1554d7161f1b79fe63021363795f05067eb723aa8a1f8eea" %}
{% set env_var = "G4LEDATA" %}
{% set summary = "GEANT4 data files for low energy electromagnetic processes" %}

{% set name = "geant4-data-"+dataset_name.lower() %}
{% set install_dir = "share/Geant4/data/"+dataset_name+version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://geant4-data.web.cern.ch/geant4-data/datasets/G4{{ dataset_name }}.{{ version }}.tar.gz
  sha256: {{ sha256 }}
  folder: dataset

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p ${PREFIX}/{{ install_dir }}
    - cp -r dataset/* ${PREFIX}/{{ install_dir }}
    - ${RECIPE_DIR}/create_activation_scripts.sh {{ name }} {{ env_var }} {{ install_dir }}

# Conda-forge is unable to build packages that have no dependencies so add
# `make` as a dummy build dependency
requirements:
  build:
    - make

test:
  commands:
    - '[ "${{ env_var }}" == "$CONDA_PREFIX/{{ install_dir }}" ]'

about:
  home: https://geant4.web.cern.ch/
  summary: {{ summary }}
  license: OTHER
  license_file: CREDIT

extra:
  recipe-maintainers:
    - tschoonj
    - chrisburr
